name: serve
description: CLI to serves static files in a directory.
version: 2.0.1
homepage: https://github.com/Jaguar-dart/serve
author: Ravi Teja Gudapati <tejainece@gmail.com>

documentation:

executables:
  serve:

environment:
  sdk: '>2.0.0 <3.0.0'

dependencies:
  jaguar: ^2.4.30
  args: ^1.5.1
  path: ^1.6.2

dev_dependencies:
  test:
