name: serve
description: CLI to serves static files in a directory.
version: 1.0.1
homepage: https://github.com/Jaguar-dart/serve
author: Ravi Teja Gudapati <tejainece@gmail.com>

documentation:

executables:
  serve:

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  jaguar: ^1.2.6
  args: ^1.2.0

dev_dependencies:
  test: ^0.12.0
