name: serve
description: CLI to serve static files in a directory as a HTTP server like Python's SimpleHTTPServer.
version: 2.0.2
homepage: https://github.com/Jaguar-dart/serve

executables:
  serve:

environment:
  sdk: '>2.8.0 <3.0.0'

dependencies:
  jaguar: ^2.4.46
  args: ^1.6.0
  path: ^1.7.0

dev_dependencies:
  test:
